### ISSUE TITLE
Error when installig Enigma (Arch Linux)

### ISSUE THREAD

**Issue by Ryah** [enigma-dev/enigma-dev#1061]
This comes up in both AUR and if I install it from the source. It quits after this error message.

```
Enigma package manager
Installing main please wait...
INFO: no dependencies for jnaJar
INFO: no dependencies for lgm
INFO: no dependencies for infolist
INFO: no dependencies for icns
INFO: no dependencies for alure
INFO: Extracting ./ENIGMAsystem/additional/alure.epackage
Traceback (most recent call last):
  File "install.py", line 101, in <module>
    downloadPackage(g_packageToInstall)
  File "install.py", line 85, in downloadPackage
    downloadPackage(dependency)
  File "install.py", line 94, in downloadPackage
    webFile = urlopen(packageURL)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by JoshDreamland** [comment]
@RobertBColton Looks like the installer had dependencies on your Dropbox. Could you send me an archive of those files so I can re-host them on ENIGMA's server?

**Comment by RobertBColton** [comment]
@JoshDreamland It uses a shared ENIGMA team Dropbox, the login credentials are posted on the staff forum.

**Comment by RobertBColton** [comment]
Closing as a duplicate, we're aware of the issue and it's been reported already:
https://github.com/enigma-dev/Enigma-packages/issues/1

The links were maintained by @amorri40 and Dropbox changed their API. We'll get this resolved, please follow the other ticket for updates.
