### ISSUE TITLE
Windows_runner_icon error persists

### ISSUE THREAD

**Issue by Hughtech** [enigma-dev/enigma-dev#1155]
I re-installed ENIGMA on my LINUX machine with all the new changes and such without any errors. However I'm still getting this error about not finding this 'windows_runner_ico.'

On the IDE side this is the error I'm getting
================================================================================
LateralGM Version: 1.8.10

Operating System: Linux
Version: 3.16.0-4-686-pae
Architecture: i386

Java Name: OpenJDK Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_151

Available processors (cores): 2
Free memory (bytes): 49152328
Maximum memory (bytes): 818413568
Total memory available to JVM (bytes): 142344192

File system root: /
Total space (bytes): 155247083520
Free space (bytes): 85061062656
Usable space (bytes): 77151289344

Stack trace:
org.lateralgm.file.GmFormatException: failed to read: /home/hughie/greakout for Linux tutorial.gmx/Configs\Default\windows\runner_icon.ico
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:470)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:295)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:233)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/hughie/greakout for Linux tutorial.gmx/Configs\Default\windows\runner_icon.ico (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.lateralgm.file.StreamDecoder.<init>(StreamDecoder.java:45)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:75)
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:466)
	... 5 more

===============================================================================
On the terminal side this is what is reported

extensions: Universal_System/Extensions/IniFilesystem,Universal_System/Extensions/Paths,Universal_System/Extensions/DateTime,Universal_System/Extensions/MotionPlanning,Universal_System/Extensions/DataStructures,Universal_System/Extensions/Alarms,Universal_System/Extensions/GM5Compat,Universal_System/Extensions/ParticleSystems,Universal_System/Extensions/Timelines

Creating swap.
Dumping whiteSpace definitions...
Opening ENIGMA for parse...
ERROR(ENIGMAsystem/SHELL/Universal_System/timelines_object.h,26,94): #error This file includes non-ENIGMA STL headers and should not be included from SHELLmain.
ERROR(ENIGMAsystem/SHELL/Universal_System/sprites_internal.h,22,92): #error This file includes non-ENIGMA STL headers and should not be included from SHELLmain.
ERROR(ENIGMAsystem/SHELL//Universal_System/sprites_internal.h,22,92): #error This file includes non-ENIGMA STL headers and should not be included from SHELLmain.
ERROR(ENIGMAsystem/SHELL//Universal_System/sprites_internal.h,22,92): #error This file includes non-ENIGMA STL headers and should not be included from SHELLmain.
Successfully loaded builtin variant type
Successfully loaded builtin var type
Successfully loaded builtin varargs type
ERROR in parsing engine file: The parser isn't happy. Don't worry, it's never happy.
ERROR: UnknownContinuing anyway.
Creating dummy primitives for old ENIGMA
Initializing EDL Parser...
Grabbing locals...
Finding parent...Found parent scope
 >> Checking ancestor object_collisions
 >> Checking ancestor object_transform
 >> Checking ancestor object_graphics
 >> Checking ancestor object_timelines
 >> Checking ancestor object_planar
 >> Checking ancestor object_basic
Determining build target...

Starting platform inspection
 - ENIGMAsystem/SHELL/Platforms/None/Info/About.ey: Opened.
 - ENIGMAsystem/SHELL/Platforms/Win32/Info/About.ey: Opened.
 - ENIGMAsystem/SHELL/Platforms/General/Info/About.ey: Failed!
 - ENIGMAsystem/SHELL/Platforms/iPhone/Info/About.ey: Opened.
 - ENIGMAsystem/SHELL/Platforms/Android/Info/About.ey: Opened.
 - ENIGMAsystem/SHELL/Platforms/xlib/Info/About.ey: Opened.
 - ENIGMAsystem/SHELL/Platforms/Cocoa/Info/About.ey: Opened.
 Done.
Thread-7: 
org.lateralgm.file.GmFormatException: failed to read: /media/hughie/120BACKUP/enigma_files/bat&ball.gmx/Configs\Default\windows\runner_icon.ico
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:470)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:295)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:233)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /media/hughie/120BACKUP/enigma_files/bat&ball.gmx/Configs\Default\windows\runner_icon.ico (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.lateralgm.file.StreamDecoder.<init>(StreamDecoder.java:45)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:75)
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:466)
	... 5 more
time taken to load file: 1,507 ms

_note: this is not the entire report, just the section that has an error._
===============================================================================

I may be wrong but this section in pointing to the path looks kind of strange (i.e  you have / then \ ) 

  java.io.FileNotFoundException: **/**media**/**hughie**/**120BACKUP**/**enigma_files/bat&ball.gmx/Configs\Default\windows\runner_icon.ico (No such file or directory)

**Comment by fundies** [comment]
This looks like a lateralgm bug please report it at https://github.com/IsmAvatar/LateralGM/issues

**Comment by RobertBColton** [comment]
> I may be wrong but this section in pointing to the path looks kind of strange (i.e you have / then \ )

No, it is correct, GameMaker Studio's IDE will not read filepaths with '/' I just tested this again the other day. If you edit any of the GMX files saved by GMS and change '\' to '/' it will error then when it tries to load a project. So LateralGM does the best it can by simply preserving the '\' instead of using '/' all the time.

Have you confirmed whether the file actually exists? And have you also tried saving the project once and reloading it, like I specified the last time?

**Comment by Hughtech** [comment]
@RobertBColton ... Yes, the file do exists. I have also done what you suggested. I am in fact writing out some tutorials for LINUX and while the GMX files load and works on my laptop which has the 'ENIGMA' installation from when I first installed last year, my other LINUX desktop which has the newer installation files and changes is the one with the reported errors.

I should mention that both have the same LINUX OS versions installed.

**Comment by RobertBColton** [comment]
I see, I'll look into it after bit, it may in fact be related to '\\' then. I did change the file path in my other changes and I may have accidentally left a '\\' outside of the toUnixPath utility function.

**Comment by fundies** [comment]
these are java errors in the gmx reader which is not part of enigmaplease take it up on the lateralgm tracker

**Comment by DarkAceZ** [comment]
🤔
