### ISSUE TITLE
Legit issue

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1261]
#1233, why is it not in master?

Also, I `git pull` after last night's merge and now even empty game crash:
```
$ ./emake -o /tmp/test.exe -r
```
```
Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffdd8754f8f in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffdd8754f8f in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffdd8717099 in ntdll!memset () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffdd86c7685 in ntdll!RtlValidateHeap ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffda326d3ac in GetHookAPIs () from C:\WINDOWS\SYSTEM32\AcLayers.dll
#4  0x00007ffdd4bb721e in LocalFree () from C:\WINDOWS\System32\KernelBase.dll
#5  0x0000000000407c2b in WinMain (hInstance=0x400000, hPrevInstance=0x0,
    lpCmdLine=0x3bd55f9 "", iCmdShow=10)
    at Platforms/Win32/WINDOWSmain.cpp:444
#6  0x00000000005e5df2 in main (flags=<optimized out>,
    cmdline=<optimized out>, inst=<optimized out>)
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18
#7  0x00000000004013c7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:331
#8  0x00000000004014fb in mainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:215
```

**Comment by RobertBColton** [comment]
This is resolved by #1262 which is merged.
