### ISSUE TITLE
ARMHF build.

### ISSUE THREAD

**Issue by FlameFireling** [enigma-dev/enigma-dev#1426]
So. i just compiled enigma-dev on raspberry pi and it worked flawlesly. but it's full of errors like when you try to edit a sprite or a background
`
LateralGM Version: 1.8.40

Operating System: Linux
Version: 4.14.71-v7+
Architecture: arm

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_65

Available processors (cores): 4
Free memory (bytes): 22043464
Maximum memory (bytes): 219021312
Total memory available to JVM (bytes): 48697344

File system root: /
Total space (bytes): 30111518720
Free space (bytes): 21835837440
Usable space (bytes): 20282662912

Stack trace:
java.lang.UnsupportedOperationException: The EDIT action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
	at java.awt.Desktop.edit(Desktop.java:300)
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.start(SpriteFrame.java:1757)
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.<init>(SpriteFrame.java:1732)
	at org.lateralgm.subframes.SpriteFrame.editSubimage(SpriteFrame.java:1695)
	at org.lateralgm.subframes.SpriteFrame.editActionsPerformed(SpriteFrame.java:1279)
	at org.lateralgm.subframes.SpriteFrame.actionPerformed(SpriteFrame.java:1363)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
and
when testing or compiling `** Error in `java': free(): invalid pointer: 0x01b240e8 ***
./start.sh: line 3:  1451 Interupted             java -Djna.nosys=true -jar lateralgm.jar "$1"
`
everything else seems to work "fine"

**Comment by RobertBColton** [comment]
Hi, thanks for reporting the issue! Unfortunately, the origin of the error message is not in this repository, it is in the LateralGM codebase. So I will need to close it here.

The issue has also been reported on the LateralGM tracker.
https://github.com/IsmAvatar/LateralGM/issues/378

Please understand that LateralGM is not being actively developed and I am working on a replacement for it with RadialGM. Thank you.
