### ISSUE TITLE
LGM crashes on startup

### ISSUE THREAD

**Issue by maiple** [enigma-dev/enigma-dev#1827]
The splash screen is shown, and then this exception occurs. I tried this on 1.6.3 and on 1.5.7.1.

```
$ java -jar lgm16b3.jar test
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.util.InputMismatchException
	at java.util.Scanner.throwFor(java.base@9-internal/Scanner.java:864)
	at java.util.Scanner.next(java.base@9-internal/Scanner.java:1495)
	at java.util.Scanner.nextInt(java.base@9-internal/Scanner.java:2129)
	at java.util.Scanner.nextInt(java.base@9-internal/Scanner.java:2088)
	at org.lateralgm.main.LGM.<clinit>(LGM.java:108)
```

I'm using 64-bit Linux Mint 18.2 "Sonya"

**Comment by RobertBColton** [comment]
What Java version? I only managed to get this in an EA release of Java 9 before. Regardless, the issue has already been patched in https://github.com/IsmAvatar/LateralGM/commit/817e2649b1a4d500940194e8af9d3579e563b02a, LGM 1.6.3 and 1.5.7.1 are really old now. Please download one of the 1.8 releases.

**Comment by maiple** [comment]
I tried downloading the Enigma-dev version (running the provided `install.sh`) and got this result:

```
$ java -jar lateralgm.jar 
Exception in thread "main" java.lang.IllegalAccessError: class org.lateralgm.main.LGM (in unnamed module @0x5a8806ef) cannot access class com.sun.imageio.plugins.wbmp.WBMPImageReaderSpi (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.wbmp to unnamed module @0x5a8806ef
	at org.lateralgm.main.LGM.<clinit>(LGM.java:170)
```

I'm jusing Openjdk-9. I'll try the Oracle version next.

**Comment by RobertBColton** [comment]
We generally don't recommend the use of OpenJDK. See open issues on LateralGM's tracker about that. We're very open minded about open source obviously, but it doesn't change the fact that OpenJDK is bug ridden compared to the proprietary Oracle JDK. That crash you just got seems to be a regression in OpenJDK with respect to its implementation of Project Jigsaw and modularity from Java 9. Yeah, please try another JDK, I am personally using Oracle JDK 9.0.4+11 for development and using ENIGMA. That one should definitely be good with the newer 1.8 releases of LateralGM.

**Comment by maiple** [comment]
Using the Oracle JDK fixes the error. Thank you very much for your help!

Can I recommend having the editor print a message if it detects OpenJDK suggesting that it may be responsible for any resulting crashes? `System.getProperty("java.vendor").startsWith("OpenJDK")` ought to work.

**Comment by RobertBColton** [comment]
Yes, I was just talking about that to somebody else. I will try to get that in with the other information from LGM's error dialog.
