### ISSUE TITLE
Error: LateralGM with Enigma installed doesn't start. Gives this error:

### ISSUE THREAD

**Issue by RadThadd** [enigma-dev/enigma-dev#1870]
LateralGM Version: 1.8.89
Working Directory: C:\enigma-dev-master\lateralgm.jar

Operating System: Windows 8.1
Version: 6.3
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 11.0.1

Current Thread: main
Available processors (cores): 4
Free memory (bytes): 39044608
Maximum memory (bytes): 1046478848
Total memory available to JVM (bytes): 67108864

File system root: C:
Total space (bytes): 781966110720
Free space (bytes): 140759838720
Usable space (bytes): 140759838720

Stack trace:
java.lang.NoClassDefFoundError: com/sun/jna/Pointer
at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
at java.base/java.lang.Class.getConstructor0(Class.java:3343)
at java.base/java.lang.Class.newInstance(Class.java:556)
at org.lateralgm.main.LGM.loadPlugins(LGM.java:705)
at org.lateralgm.main.LGM.main(LGM.java:1167)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Pointer
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 6 more

**Comment by RobertBColton** [comment]
This was solved by us fixing the 404 of JNA.
https://github.com/enigma-dev/ExtraPackages/commit/c51eea6951d973d931741c5151ac1b275b7e43fb

**Comment by fundies** [comment]
the link needs updating install.sh too
