### ISSUE TITLE
Windows 8.1 - ENIGMA LGM plugin runtime error

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [enigma-dev/enigma-dev#782]
I'm not sure whether this is the right place to submit this issue... don't blame me if I'm wrong.
# Initial setup

I'm trying to build ENIGMA on Windows 8.1 using the `Source Code` section at http://enigma-dev.org/docs/Wiki/Install:Windows. I have MinGW already installed. This is what I get for running `gcc -v`:

```
Using built-in specs.
COLLECT_GCC=c:\Program Files (x86)\devc\MinGW32\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/program files (x86)/devc/mingw32/bin/../libexec/gcc/mingw32/4.7.2/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.7.2/configure --enable-languages=c,c++,ada,fortran,objc,obj-c++ --disable-sjlj-exceptions --with-dwarf2 --enable-shared --enable-libgomp --disable-win32-registry --enable-libstdcxx-debug --disable-build-poststage1-with-cxx --enable-version-specific-runtime-libs --build=mingw32 --prefix=/mingw
Thread model: win32
gcc version 4.7.2 (GCC) 
```

After downloading  https://github.com/enigma-dev/enigma-dev/archive/master.zip and https://dl.dropboxusercontent.com/u/21117924/WinPatch_28_08_2013.zip I ran the following in gitbash (I'm using Git-1.8.4-preview20130916):

```
$ cd ws/sb/
$ unzip enigma-dev-master.zip
$ unzip WinPatch_28_08_2013.zip
$ ENIGMA.exe
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
Checking Java Installation
Setting Environment Path
PATH=c:/Users/Medicijnman/ws/sb/mingw32/bin;c:\Users\Medicijnman\bin;.;C:\Program Files (x86)\Git\local\bin;C:\Program Files (x86)\Git\mingw\bin;C:\Program Files (x86)\Git\bin;c:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;c:\windows\system32;c:\windows;c:\windows\System32\Wbem;c:\windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;c:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;c:\Program Files\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;.;c:\WINDOWS\system32;c:\WINDOWS;c:\WINDOWS\System32\Wbem;c:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;c:\Program Files\doxygen\bin;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;c:\Program Files\Java\jdk\bin\;c:\Program Files\Java\jre8\bin\;c:\Program Files (x86)\devc\MinGW32\bin\;c:\Users\Medicijnman\ws\bin\;c:\Users\Medicijnman\Downloads\android-ndk-r9d\
Setting Working Directory To:c:/Users/Medicijnman/ws/sb/
java -jar "c:/Users/Medicijnman/ws/sb/lateralgm.jar" ""
$
```
# Observation

After gitbash regains focus (i.e. ENIGMA.exe terminates), LGM pops up but keeps locked at about 95%
![enigma_lgm_crash](https://cloud.githubusercontent.com/assets/5989565/3765895/9b47398a-18bf-11e4-83a9-31e912abdea7.png)
I killed LGM and ran it directly through gitbash:

```
$ java -jar lateralgm.jar
Java Version: 10800 (1.8.0_05)
Couldn't find class for specified look and feel:com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Did you include the L&F library in the class path?
Using the default look and feel.
Loading lib files in C:\Users\Medicijnman\ws\sb\lateralgm.jar
01_move.lgl 02_main1.lgl 03_main2.lgl 04_control.lgl 
 05_score.lgl 06_extra.lgl 07_draw.lgl 
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:64)
    at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:55)
    at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:347)
    at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
    at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:657)
    at org.lateralgm.main.LGM.addPluginResource(LGM.java:618)
    at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:302)
    at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:132)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:433)
    at org.lateralgm.main.LGM.loadPlugins(LGM.java:514)
    at org.lateralgm.main.LGM.main(LGM.java:788)
Caused by: java.lang.NullPointerException
    at org.enigma.TargetHandler.scoreCombo(TargetHandler.java:213)
    at org.enigma.TargetHandler.access$0(TargetHandler.java:206)
    at org.enigma.TargetHandler$Combo.finish(TargetHandler.java:256)
    at org.enigma.TargetHandler.dependencyResolution(TargetHandler.java:148)
    at org.enigma.TargetHandler.load(TargetHandler.java:65)
    at org.enigma.TargetHandler.<clinit>(TargetHandler.java:53)
    ... 15 more
```

I noticed that this might be causing the problem:

```
Couldn't find class for specified look and feel:com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Did you include the L&F library in the class path?
```

However, using

```
java -Dswing.defaultplaf=com.sun.java.swing.plaf.windows.WindowsLookAndFeel -jar lateralgm.jar
```

still gives me the stacktrace. I didn't try to run it on my mac with JRE6, but that thing is old as shit and probably can't compile enigma...
# Conclusion

I think I did everything mentioned in the `Source Code` section on the `Install:Windows` wiki page properly. I don't know how to fix this. A couple of months ago, I tried the portable enigma executable, but that didn't work either (I don't know the details anymore, I can try that again if you'd like me to). Maybe I will try to compile enigma on my old mac, but I'd rather not.

**Comment by RobertBColton** [comment]
I do not know what was wrong with me, but this is actually still an issue. I've now scoped #743 to address this issue.
